# Generated by Django 5.0 on 2023-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='urlimg',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
